### ISSUE TITLE
If several wikipedia links, include first paragraph of all

### ISSUE THREAD

**Issue by Erbros** [acini/autowikibot-py#2]
Yeah, not much else to add here.

**Comment by acini** [comment]
I thought of creating a loop for that previously, but the bot might post huge wall of text and it may look spammy. Besides, most users post single links to wikipedia.

I will try to add such loop by next milestone, if it seems feasible.

**Comment by Erbros** [comment]
Yeah, perhaps have some limit so it won't get extremely spammy. It's really
up to you, just adding my opinion ;)
