### ISSUE TITLE
Code Quality Issue [Line 48 - autowikibot-commenter.py]

### ISSUE THREAD

**Issue by fourohfour** [acini/autowikibot-py#34]
The line is this:

```
if str(e) == '(TOO_LONG) `this is too long (max: 15000.0)` on field `text`':
```

Fair enough, but I feel that if PRAW changed the error messages slightly (for example if the max comment length was changed) then this would break. Would it be better to match the String TOO_LONG with a regex?

Just a thought

-404

**Comment by acini** [comment]
Hmm, it is just a backend issue; thanks for suggesting.
