### ISSUE TITLE
Author is always Nonetype when the subreddit is not /r/all

### ISSUE THREAD

**Issue by Timidger** [acini/autowikibot-py#35]
When I run autowikibot with another subreddit (such as runescape), I can't get the author's name. I have looked at the [docs](http://burntsushi.net/stuff/praw/helpers.m.html#praw.helpers.comment_stream), and I can't find any restriction on the subreddit, a google-ing the issue does not help at all. I've changed the bot identification string and set up the configuration file (with the comments on Reddit)

```
$ ipython2 autowikibot-commenter.py runescape
[2014-07-13 12:05:44] LOGGED IN
[2014-07-13 12:05:52] DATA LOADED
Traceback (most recent call last):
 File "/home/timidger/Projects/WikiaBot/autowikibot-commenter.py", line 395, in <module>
    if filterpass(post):
  File "/home/timidger/Projects/WikiaBot/autowikibot-commenter.py", line 166, in filterpass
    if (post.author.name == USERNAME) or post.author.name in banned_users:
AttributeError: 'NoneType' object has no attribute 'name'
[2014-07-13 12:06:13] GLOBAL: 'NoneType' object has no attribute 'name'
```

**Comment by acini** [comment]
This error simply means there is no object as `post.author`. I have seen this happen when the post being referred to 
1. is either in private subreddit (when reddit returns null object)
2. is deleted

Try printing value of `post.body`.

**Comment by Timidger** [comment]
Ok, yeah it seems to work fine I guess... I thought that all those errors indicated that it wasn't working. Though is it normal for it to keep returning a `403: Forbidden` after a little bit? Is that a praw limitation or is it just finding deleted comments/posts?

**Comment by acini** [comment]
`403:Forbidden` is returned when bot tries to post in banned sub.
